### ISSUE TITLE
[carbon dashboard] Content Changes - Tokenized vs Digital

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/dash-apps#102]
As part of the move from talking about Digital Carbon vs Tokenized Carbon we are doing a scrub of the Carbon Dashboard and looking for content that needs to change.

Each change is being left as a "to-do" in a comment.

**Comment by jabby09** [comment]
**Digital Carbon page**

- [ ] Change "KlimaDAO is holding 16,727,444 carbon assets, making them the largest single holder of tokenized carbon assets." to "KlimaDAO is holding 16,727,443 carbon assets, making them the largest single holder of digital carbon assets."

**Comment by jabby09** [comment]
**ToC/Menu**

- [ ] Change page title link from "Digital Carbon" to "Digital Carbon Overview"

**Comment by jabby09** [comment]
**Digital Carbon page**

- [ ] Change "To date, iFood has retired 115,089 tokenized carbon credits, making them the current leader in tokenized carbon retirements." **TO** "To date, iFood has retired 115,089 digital carbon credits, making them the current leader in digital carbon retirements."

**Comment by jabby09** [comment]
**Carbon Pricing page**

- [ ] Change page title from "Carbon Pricing" to "Digital Carbon Pricing"

**Comment by jabby09** [comment]
**Carbon Supply page**

- [ ] Change page title from "Carbon Supply" to "Digital Carbon Supply"

**Comment by jabby09** [comment]
@originalpkbims I think this issue is good to go.

**Comment by originalpkbims** [comment]
PR to review: https://github.com/KlimaDAO/dash-apps/pull/98

**Comment by jabby09** [comment]
Looks good!
