### ISSUE TITLE
Add '#buildwithklima' banner at the top of the carbon dashboard

### ISSUE THREAD

**Issue by abonn** [KlimaDAO/dash-apps#103]
Include banner text similar to what was utilized on the main Klima website for promoting the DCM webinar with a link to our RA documents to increase the awareness of these resources.

**Comment by 0xAurelius** [comment]
we did the Onset webinar banner, so going to close this ticket in favor of a more specific ticket to add some CTA (call-to-action) links to the sidebar - maybe direct people to Carbonmark to browse specific projects
