### ISSUE TITLE
Add error handling to Subgrounds data fetches

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/dash-apps#105]
We need to handle subgraphs being unavailable more gracefully than we currently do - ideally wrap each subgrounds query in a `try/except` that ensures _something_ is passed back from the data fetching functions, for instance `None`

And then in the process of rendering each chart, we check if the dataset we're using is `None` - and if so simply display a generic "This dataset is not available at the moment" message

**Comment by jabby09** [comment]
From pkbims...

> I can can take this. Error handling seems high priority at the moment.
> Also how about having a weekly backup so instead of “No Dataset”, we can say dataset not uptodate somewhere and show results.

**Comment by jabby09** [comment]
From marcus...

> sure, we already have a backup Verra dataset in DigitalOcean, I like this as a stopgap solution until we have a data pipeline in place

**Comment by jabby09** [comment]
[Proposed solution and requirements](https://www.notion.so/klima-dao/Carbon-Dashboard-Error-Handling-35085ab575b44395976a1bc58c4faa80)

**Comment by jabby09** [comment]
[Roadmap workstream card](https://www.notion.so/klima-dao/carbon-dashboard-Add-Error-Handling-to-Subgrounds-Data-Fetches-924cb4d8853d462b8ae823286675c916)

**Comment by jabby09** [comment]
again likely no longer need with new upgraded data pipeline and new klima data frontend.
