### ISSUE TITLE
Clarify pool vs. project on retirement trends page

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/dash-apps#122]
Right now we just have a "Pool" column that either shows a pool name or a TCO2 address

Instead, we should have a separate "Project" column that links directly to the Verra project page (or maybe the project page on Carbonmark?) and then Pool would be blank or `N/A` for retirements made directly via TCO2

**Comment by JamesAttwood1910** [comment]
Hey @0xAurelius @jabby09 I've looked into this and have a solution worked out. In summary as below...

For the project column:
- on the klimaDAO graph get the projectID from the offset object within klimaretires 
- paste the project number on the end of a standard link to the verra registry e.g.  https://registry.verra.org/app/projectDetail/VCS/1188
- this link is displayed in the project column.

For the existing pools column: 
- Set any TC02 strings to N/A 

Only questions I have are: 
- Some retirements have a blank project id in the graph. Shall we display N/A in the project column here? 
- Some pools values are 0x0000000000000000000000000000000000000000. These seem out of sync with the standard TC02 string formats, although do come back with results in klimaretires, but with missing projectIDs as well. Any ideas what they relate to?

**Comment by JamesAttwood1910** [comment]
This image provides some context to my two questions: 
<img width="1014" alt="Screenshot 2023-05-04 at 23 01 05" src="https://user-images.githubusercontent.com/60195529/236342733-d119510f-e9c2-4abd-829f-d6ea42ac00c2.png">

**Comment by JamesAttwood1910** [comment]
In terms of time my estimate is: 
- 2 hours thinking through above solution (already done)
- 1 hr implementing solution in code 
- 30 mins task admin (making commits, PR, formatting code etc)

**Comment by 0xAurelius** [comment]
Great, sounds reasonable

There are some minor issues with the subgraph data that @cujowolf has been working through, so some of these inconsistencies may be a result of those

They should be fixed soon, I think displaying N/A if the pool ID is not populated is fine but let's just ignore the 0x0 thing for now since I think it's an issue with the way MCO2 retirements are handled 

In terms of formatting the project link, we should use markdown to format the link like this: `[VCS-1234]( https://registry.verra.org/app/projectDetail/VCS/1188)]`

Make sense?

**Comment by JamesAttwood1910** [comment]
Great, makes sense thanks! I'll leave the 0x0 as are, put any missing project IDs as N/A and format the links with markdown.

**Comment by JamesAttwood1910** [comment]
Hey @0xAurelius see PR 135 above
