### ISSUE TITLE
Add "By Beneficiary" tab to retirement trends

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/dash-apps#123]
Totals by beneficiary, date of first/last retirement, % of pledge fulfilled, etc.

Provides an effective leaderboard for pledges too

**Comment by jabby09** [comment]
@theprofessora will need a design for this next enhancement

**Comment by 0xAurelius** [comment]
This should be pretty similar to the other Retirement Trends pages, but will have some different columns in the table related to beneficiary level details like whether the user has claimed their pledge or not

I'm not exactly sure how much data about pledges we can fetch directly, but that's more a data problem that we can work out in implementation

**Comment by theprofessora** [comment]
Ready for review: https://www.figma.com/file/mXI4SzNNmoefYnOdcbXZcO?node-id=1941:1972#419836519

**Comment by jabby09** [comment]
@0xAurelius see design above for review
