### ISSUE TITLE
Log scale option on line graphs

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/dash-apps#125]
Where applicable and across all the pages, include a log scale option for the line graphs.

This will help better visualize the data when the graph includes outlier/extreme values that mute the rest of the chart, for example.
![Screenshot 2023-03-28 at 9 34 10 AM](https://user-images.githubusercontent.com/103535195/228237520-3af4aeb8-e208-4929-8206-58b921ae9cbe.png)

**Comment by JamesAttwood1910** [comment]
Hey @jabby09 and @0xAurelius I have a solution for this for the KlimaDAO retirements by Token and by Chain graphs. I'm away the next few days but will submit the PR early next week.

**Comment by jabby09** [comment]
This is will be managed now in the new Klima Data app.
