### ISSUE TITLE
Improve definitions of  'retirement' and 'redemption'

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/dash-apps#126]
On the Retirements Trends page...https://carbon.klimadao.finance/retirements
In particular BY POOL tab...

Supplement info tooltips to expand/refine the definitions of 'retirement' and 'redemption'.

**Comment by jabby09** [comment]
@ChazSchmidt not product docs per se but wondering if this an area you can help with, we need tool tip content for this issue.

**Comment by jabby09** [comment]
@ChazSchmidt any progress on these definitions? thanks

**Comment by ChazSchmidt** [comment]
@jabby09 PR here with expanded definition https://github.com/KlimaDAO/dash-apps/pull/146/commits/e8f3c1eca78437349c20121518d0a0a018469715

**Comment by jabby09** [comment]
> 

@ChazSchmidt thanks...what do I need to do with that commit? Or did you already hook that up to tool tips in the PR?

**Comment by ChazSchmidt** [comment]
@jabby09 I need permissions to the dash-apps repo in order to push the commit
`Permission to KlimaDAO/dash-apps.git denied to ChazSchmidt.`

**Comment by jabby09** [comment]
> @jabby09 I need permissions to the dash-apps repo in order to push the commit
> `Permission to KlimaDAO/dash-apps.git denied to ChazSchmidt.`

@ChazSchmidt as discussed, think you need to connect with @0xAurelius for this one
