### ISSUE TITLE
Add links to Carbonmark and broader KlimaDAO ecosystem

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/dash-apps#129]
There should be some call-to-action link on the dashboard that leads people to Carbonmark for browsing projects and buying/selling/retiring credits.

followup to #103

**Comment by 0xAurelius** [comment]
I'm thinking we could replace all links to the Verra project detail pages with links to the corresponding Carbonmark pages... only trouble is that the Verra pages are by project whereas the CM pages are by project/vintage...

**Comment by cupidbow20000** [comment]
Hello
do you need a dev?

**Comment by jabby09** [comment]
address as part of carbon dashboard redesign
