### ISSUE TITLE
Design Tooltips for Carbon Dashboard

### ISSUE THREAD

**Issue by theprofessora** [KlimaDAO/dash-apps#169]
the stock tooltips on the carbon dash don't seem to be getting the job done as eloquently as originally expected. need something a little bit more custom

**Comment by theprofessora** [comment]
@biwano @sprrwhwk here's the link for an updated tooltip: https://www.figma.com/file/mXI4SzNNmoefYnOdcbXZcO?node-id=3086:9718&mode=design#536606214

**Comment by sprrwhwk** [comment]
@jabby09 I believe this can be closed, right?
