### ISSUE TITLE
Carbon Dashboard HomePage

### ISSUE THREAD

**Issue by originalpkbims** [KlimaDAO/dash-apps#55]
Aaron created designs for the carbon dashboard homepage; https://www.figma.com/file/mXI4SzNNmoefYnOdcbXZcO/The-State-of-Tokenized-Carbon?node-id=901%3A1440

Create a Homepage similar to the design, there might be some limitations in using plotly.

**Comment by jabby09** [comment]
@originalpkbims (and Aaron)...another approach to this was discuss in our last Product Sync meeting:

- Another approach…what about just drawing a 2d circle
    - Just looking for the viz to be a representation
    - See original Sy sketch
    - 2d circle drawn with css or just a graphic with dynamic numbers within them
    - Would there be a maintenance burden of updating this?
        - Not really, just the dynamic number that would change, not the graphic overlay
    - Circles can then collapse vertically on mobile
    - And then can get more creative on retirement, doing something like beads
    - Dash has ability to draw graphics natively

**Comment by jabby09** [comment]
@aarongillett assigned to you and labeled with design needed

**Comment by jabby09** [comment]
Moved to Blocked/Waiting, need an update from @aarongillett

**Comment by jabby09** [comment]
@originalpkbims Design updates are completed. We are going forward with Option 2 (Combined Bubble Charts) https://www.figma.com/file/mXI4SzNNmoefYnOdcbXZcO/The-State-of-Tokenized-Carbon?node-id=1288%3A918

As discussed, with these design the circles are infographics but the text labels should be live data (i.e. the text updates, but the circles remain static).

Please let us know if you need a design --> dev handoff meeting to discuss anything.
