### ISSUE TITLE
[carbon dashboard] Apply updated font/style changes across all pages

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/dash-apps#87]
The purpose of this ticket is to consistently apply recommended style and font changes across the Carbon Dashboard site. 

These are the requirements and should be applied to all relevant components across all of the pages:

- [x] For the header cards, please use the following:

```
Width: 100%
padding top and bottom: 20px
```
Font: “Desktop/H2” - 48px Bold

```
font-family: 'Poppins';
font-style: normal;
font-weight: 700;
font-size: 48px;
line-height: 48px;
```

- [x] For the number cards, please use the following:

`padding top and bottom: 20px`
make the labels font “Desktop/H5”

```
font-family: 'Poppins';
font-style: normal;
font-weight: 700;
font-size: 20px;
line-height: 28px;
```

The space between the labels and their corresponding numbers should be 12px
Make the numbers font:

```
font-family: 'Inter';
font-style: normal;
font-weight: 400;
font-size: 20px;
line-height: 24px;
```

- [x] For the graph cards, please use the following:

`padding-all: 20px`
Graph titles:

```
font-family: 'Poppins';
font-style: normal;
font-weight: 700;
font-size: 20px;
line-height: 28px;
```

- [x] Space between cards within a chain grouping (for example all the cards relating to the polygon on chain carbon), should be 20px. Space between chain groupings should be 40 px. (So the ethereum title card should be 40 px below the bottom polygon graph card, etc)

**Comment by jabby09** [comment]
@originalpkbims here you go!

**Comment by jabby09** [comment]
PR to review: https://github.com/KlimaDAO/dash-apps/pull/98

**Comment by ShimonD-KlimaDAO** [comment]
Left feedback on #98 
CC @0xAurelius @originalpkbims @jabby09

**Comment by jabby09** [comment]
hi @theprofessora when you get a minute can you please add the feedback you gave pkbims in a comment on the ticket. thanks!

**Comment by theprofessora** [comment]
Thanks for the reminder

**1. Header Cards:**
```
font-family: var(--font-fam-Poppins); 
font-style: normal; 
font-weight: 700; 
font-size: 48px; 
line-height: 48px;
```

**2. Number Cards**
_2.1 Label_
```
font-family: var(--font-fam-Poppins); 
font-style: normal; font-weight: 700; 
font-size: 20px; 
line-height: 28px; 
text-align: center; 
```
_2.2 Number_
```
font-family: var(--font-fam-Inter); 
font-style: normal; 
font-weight: 400; 
font-size: 20px; 
line-height: 24px; 
text-align: center;
```

**3. Graph Cards**
_3.1 Labels_
```
font-family: var(--font-fam-Poppins); 
font-style: normal; 
font-weight: 700; 
font-size: 20px; 
line-height: 28px; 
text-align: center; 
justify-content: center;
```
_3.2 Graph data_
```
font-family: 'Inter';
font-style: normal;
font-weight: 500;
font-size: 8px;
line-height: 12px;
```

**4. Holdings & Retirements paragraphs:**
_4.1 normal text_
```
font-family: 'Inter';
font-style: normal;
font-weight: 300;
font-size: 36px;
line-height: 48px;
```
_4.2 org name and number held/retired_
```
font-family: 'Inter';
font-style: normal;
font-weight: 700;
font-size: 36px;
line-height: 48px;
```

**Comment by jabby09** [comment]
@originalpkbims @ShimonD-KlimaDAO this looks good to me now.

My only question is could we bump the ToC width enough to get Digital Carbon Overview on one line?

![Image](https://user-images.githubusercontent.com/103535195/215772134-5aea3387-ef43-4353-81b0-52ca152beb52.png)

**Comment by jabby09** [comment]
Related PR: #98
