### ISSUE TITLE
[carbon dashboard] URL is case sensitive

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/dash-apps#99]
Submitted via [discord](https://discord.com/channels/841390338324824096/964698508751949824/1062704611154206770)

The URLs for carbon.klimadao.finance are set to be case sensitive. This means it's very difficult to directly navigate or even link to them.

Works => https://carbon.klimadao.finance/CarbonPricing
Doesn't work => https://carbon.klimadao.finance/carbonpricing

In addition, the URL really should be /carbon-pricing  with a hyphen, so that we can rank for the keyword carbon / carbon pricing

**Comment by jabby09** [comment]
@ShimonD-KlimaDAO marcus fixed the hyphenated URLs and added redirects to staging so this is ready for QA

https://staging-carbon-dashboard-9yimq.ondigitalocean.app/

**Comment by ShimonD-KlimaDAO** [comment]
Adding note from discord for the record:

> I see that carbon-market works, but there is no redirect from carbonmarket to carbon-market. Also, the URL is still case-sensitive.
> For example, https://carbon.klimadao.finance/carbon-markEt doesn't resolve to the carbon-market page.

Should we re-open?
